<div class='span12'>

	<div class='span6 well'>
		<form  method='post'  action='' enctype='multipart/form-data'>		
		<input type='hidden' value='1' name='q_update'>
		<div class='span12'>
			<h3>
				Edit Quiz Question.
			</h3>
				<p><input type="text" name='title' class='span10' required value='<?=$this->question->title?>' placeholder="Question Title, this is optional"  ></p>
				<p><input type="text" name='description' class='span10' required value='<?=$this->question->description?>' placeholder="Question description, this is optional" ></p>
				<br>
				<hr>
				Image, if any:
				<p>
					<input type='file' name='image'>
				</p>
				
				<?php
					if($this->question->image){
						echo "<div class='thumbnail span3'><span ><a href='' class='text text-error'>Delete Image</a></span><img src='".HTTP.WWW_ROOT."/uploads/".$this->question->image."'></div>";
					}
				?>
				<div class='row'></div>
				<br>
				<hr>
				Vimeo Video URL, if any ( e.g. <span class='text text-success'>http://player.vimeo.com/video/25451551</span> ):
				<p>
					<input type='text' class='span6' name='video' value='<?=$this->question->video?>' placeholder='Vimeo video url here'>
				<small class='muted'>Empty this text to delete video</small>
				</p>
				<?php
					if($this->question->video){
				?>
					<div class='thumbnail span3'>
					<iframe 
						src="<?=$this->question->video?>" 
						width="200" 
						height="100" 
						frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
					</iframe>
					</div>
				<?php
					}
				?>
				<br>
				<div class='row'></div>
				<br>
				<button type="submit" class="btn btn-primary"> Submit </button>
						
		</div>
		</form>
	
	</div><!-- span6 -->
		
	<div class='span6 well alert'>
		<?php
			if($this->no_answer){
				echo "<strong>No Answers added yet. Please follow below process to add answer.</strong>";
			}
			else{
				echo "<strong>Following answers already exists. The one with RED BORDER is marked correct by you.</strong><br><br>";
				switch($this->type){
					
					case Model_DbTable_Answer::IMAGESERIES:
						foreach($this->existingAnswers as $key=>$value){
							// mark green for correct
							if($value['is_correct']){
								$css = "style='border:4px solid #cc2211'";
							}
							
							// show all answers
							echo "<div class='span2 thumbnail ' {$css}>
								<img src='".HTTP.WWW_ROOT."/uploads/".$value['data']."'>
							</div>";
							$css = '';
						}
						break;
					case Model_DbTable_Answer::TRUEFALSE:
						foreach($this->existingAnswers as $key=>$value){
							// mark green for correct
							if($value['data']){
								echo '<h4 class="btn disabled btn-success"><strong>The answer is TRUE</strong></h4><br><br>';
							}
							else{	
								echo '<h4 class="btn disabled btn-danger"><strong>The answer is FALSE</strong></h4><br><br>';
							}					
						}
						break;
					case Model_DbTable_Answer::MULTICHECK:
						foreach($this->existingAnswers as $key=>$value){
							// mark green for correct
							if($value['is_correct']){
								$css = "style='border:4px solid #cc2211'";
							}
							
							// show all answers
							echo "<div class='span3 alert alert-success' {$css}>
								".$value['data']."
							</div>";
							$css = '';
						}
						break;
					case Model_DbTable_Answer::TEXT:
						echo "<div class='span2 thumbnail {$css}'>
							".$this->existingAnswers[0]."
						</div>";
						break;
					default:
						
				}
				echo "<div class='row-fluid'><div class='span12'><a class='text text-error' href='".HTTP.WWW_ROOT."/admin/quiz/delete-all-answers/id/".$this->question->id."'><strong><i class='icon icon-remove'></i> Reset Answers ! This will delete existing answers.</strong></a></div></div>";
			}
		?>	
		
		<?php
			if(!$this->step && $this->no_answer){
			?>
			<div class='row-fluid'>
				<div class='span12 well'>
					<form  method='post'  action='' enctype='multipart/form-data'>	
					<input type='hidden' name='step' value='2'>	
					<div class='span12'>
						<h3>
							Add Answers for Above Question.
						</h3>
						Select the type of Answers:
						<p>
						<select name='answer_type'>
							<option value='<?=Model_DbTable_Answer::TEXT?>'>Text Field</option>
							<option value='<?=Model_DbTable_Answer::TRUEFALSE?>'>True or False</option>
							<option value='<?=Model_DbTable_Answer::MULTICHECK?>'>Multiple CheckBox Options</option>
							<option value='<?=Model_DbTable_Answer::IMAGESERIES?>'>Series of Images</option>
						</select>
						</p>
						How many options ? 
						<span class='text text-error'>(Enter '1' for textbox and true/false)</span>
						<p>
							<input type='text' required class='text' name='qty' value='1' >
						</p>
						<button type="submit" class="btn btn-info"> Next Step >> </button>
									
					</div>
					
					</form>
				
				</div>		
			</div>
			<?php
			}
			?>
			
			<?php
			if($this->step == 2){
				
			?>
			<div class='row-fluid'>
				<div class='span12 well'>
					<form  method='post'  action='' enctype='multipart/form-data'>	
					<input type='hidden' name='step' value='3'>	
					<input type='hidden' name='q_answer' value='1'>
					<div class='span12'>
						<h3>
							Add Answers.
						</h3>
			
						<?php
						// if uploading image
						if($this->answer_type == Model_DbTable_Answer::IMAGESERIES){
							echo "<input type='hidden' name='switch_answer' value='".Model_DbTable_Answer::IMAGESERIES."'>";
							echo "Upload Image for Answer:<br>";
							for($i = 1; $i <= $this->qty ; $i++){
								echo "<div class='well'>";
								echo "<input type='file' name='image_answer_{$i}'><br>";
								echo "<label class='checkbox'>
									<input type='checkbox' value='1' name='options_is_correct[{$i}]'>Is this Correct Option?</label>";
								echo "</div>";
							}
						}
						
						// if setting multiple checkbox
						if($this->answer_type == Model_DbTable_Answer::MULTICHECK){
							echo "<input type='hidden' name='switch_answer' value='".Model_DbTable_Answer::MULTICHECK."'>";
							echo "Enter text for Multiple options:<br>";
							for($i = 1; $i <= $this->qty ; $i++){
								echo "<div class='well'>";
								echo "<input type='text' name='options_answer[{$i}]'><br>";
								echo "<label class='checkbox'>
									<input type='checkbox' value='1' name='options_is_correct[{$i}]'>Is this Correct Option?</label>";
								echo "</div>";
							}
						
						}
						
						// if true false
						if($this->answer_type == Model_DbTable_Answer::TRUEFALSE){
							echo "<input type='hidden' name='switch_answer' value='".Model_DbTable_Answer::TRUEFALSE."'>";
							echo "<div class='well'>";
							echo "<label class='checkbox'>
									<input type='checkbox' name='truefalse_answer'>Check if your Question is true</div>";
							echo "</label>";
						}
			
						// if textbox
						if($this->answer_type == Model_DbTable_Answer::TEXT){
							echo "<input type='hidden' name='switch_answer' value='".Model_DbTable_Answer::TEXT."'>";
							echo "<div class=''>
								<input type='text' name='text_answer' class='span10' placeholder='type correct answer here'></div>";
						}
						
						
						?>
						<button type="submit" class="btn btn-primary"> Submit </button>
						<a href='<?=HTTP.WWW_ROOT?>/admin/quiz/list' class="btn"> Cancel, I will do later! </a>
									
					</div>
					
					</form>
						
			</div>	
			<?php
			}
			?>
			

	</div>		


</div>

