<style>
.page{
	padding: 1px;
	padding-left: 10px;
	padding-right: 10px;
	font-size: 12px;
	color: #444;
	
}
.page:hover{
	color: #cc2222;
	cursor: pointer;
}
</style>
<?php if ($this->pageCount): ?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a class="page" href="<?php echo $this->url(array('page' => $this->previous)); ?>">
    &lt; Previous
  </a> 
<?php else: ?>
  <span class="btn page disabled">&lt; Previous</span> 
<?php endif; ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a class="btn page" href="<?php echo $this->url(array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a> 
  <?php else: ?>
    <span class="btn page" id="current_page"><?php echo $page; ?></span> 
  <?php endif; ?>
<?php endforeach; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a class="btn page" href="<?php echo $this->url(array('page' => $this->next)); ?>">
    Next &gt;
  </a>
<?php else: ?>
  <span class="btn page" class="disabled">Next &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>


