<div class='span12'>

	<div class='row-fluid'>
			<div class='row-fluid'>
				<div class='span12'>
					<div class='alert alert-success'> 
					<h4>You are now a Trainee of <?=$this->trainer->first_name?> <?=$this->trainer->last_name?></h4>
					</div>	
					<div class='alert alert-info'> 
						Your Trainer will be able to check your Meal Plans and suggest accordingly.
					</div>	
					
				</div>		
			</div>
			
	</div>

</div>


