<div class='span1'>
</div>
           
<div class='span10 white-panel'>
	<h3>
		Change Password.
	</h3>
	<hr>		
	
	<div class='row-fluid'>
		
		<form  method='post'  action='' enctype='multipart/form-data'>		
			<?php
			if($this->err){
				echo "<div class='alert alert-error'>{$this->err}</div>";
			}
			if($this->msg){
				echo "<div class='alert alert-success'>{$this->msg}</div>";
			}
			?>
			<div class='row-fluid'>
				<div class='span12 '>
					<div class='span4'>
					</div>
					<div class='span4'>
					
						<p><input rel="tooltip" data-placement="top" data-trigger="hover" type="password" name='password' required placeholder="New Password"></p>			
						<p><input type="password" name='c_password' required placeholder="Confirm Password" rel="tooltip" data-placement="top" data-trigger="hover"  ></p>
										
					</div>
					<div class='span4'>
					</div>				
				</div>		
			</div>
			
			<div class='row-fluid'>
				<div class='span12'>
					<hr>
				</div>
			</div>
			
		
			<button type="submit" class="btn btn-primary pull-right"> <i class="icon icon-edit icon-white "></i> Update </button>
							
		</form>
		
	</div>

</div>
<div class='span1'>
</div>



