<div class='row-fluid'>
	
	<div class='span8'>
		<div class='white-panel'>
			<h3 class='blue'>	
				Its all about how to start a project and a make a Solid Foundation for it.
			</h3> 
			<hr>
			<p >
			Being programmers, we must have asked ourselves below questions in one of more scenarios!
			</p>
			<h5 class='blue'>
			 <ul>
			 	<li> How do I start this project?</li>
				<li> What framework should I use? </li>
				<li> What if I ever got stuck in the middle?</li>
				<li> Is my DB design good enough?</li>
				<li> Are my coding standards good enough </li>
			</ul>
			</h5>
		</div>
		<h1>
			Every <span class='blue'>ProjectPacket</span> is build around these problems. 
		</h1>
	</div>

	<div class='span4'>
		<img src='<?=HTTP.WWW_ROOT?>/res/img/512/shield_512.png'>
	</div>
	
</div>

<div class='row-fluid'>
	<div class='span12'>
		<br>
		<hr>
		<br>
	</div>
</div>
<div class='row-fluid'>
	
	<div class='span4'>
		<img src='<?=HTTP.WWW_ROOT?>/res/img/512/package_gear_512.png'>
	</div>

	<div class='span8'>
		<div class='white-panel'>
			<h3 class='blue'>	
				Whats inside A Packet?
			</h3> 
			<hr>
			<p >
			We carefully build and pack very project with following.
			</p>
			<h5 class='blue'>
			 <ul>
			 	<li> Only top of the line Framework are being used.</li>
				<li> Strict Framework code guidelines as per the Framework being used. </li>
				<li> Optimized Database design and Schema within the Packet.</li>
				<li> Doc style code comments.</li>
				<li> Best possible CSS/HTML Framework e.g. Bootstrap, jQuery, etc.</li>
				<li> Atleast one set of Form, Auth, Search and Listing</li>
				<li> Complete Project is responsive.</li>
				<li> Each Project has Admin Panel to start with.</li>
				<li> A document on how to install the packet.</li></li>
				<li> And every packet is under GPL. <a href='<?=HTTP.WWW_ROOT?>.' class='red'>Read more about GPL here.</a></li>
				<li>And if you are subscribed, you will get informed when any ProjectPacket is added or updated.</li>
			</ul>
			</h5>
		</div>
		<h1>
			Its A <span class='blue'>Recipe</span> that everyone needs. 
		</h1>
	</div>

	
</div>


