<div class='span12'>

	<h3>Current Quiz Session Over</h3>
	<hr><br>
	
	<div class='row-fluid'>
		<div class='span12'>
			<div class='alert alert-info'> <strong><h4>Current session of Quiz is finished, but you can start the quiz again.</h4></strong></div>
			<a class='btn btn-success btn-large' href='<?=HTTP.WWW_ROOT?>/user/quiz/start-new-quiz'>Start New Brain Quiz</a>

		</div>		
	</div>
	
</div>


