<div class='span1'>
</div>

<div class='span10 white-panel'>

	<h3>
		Thank You.
	</h3>
	
	<hr>		
	
	<div class='row-fluid'>
		
		You account has been created. You can now create you Meal Plans.
		<br><br>
		<a class='btn btn-info' href='<?=HTTP.WWW_ROOT?>/login'>Click Here To Login & View Your Meal Plans</a>
		<br>		
		<br>
		Support.
		
		<br>
		<?=APP_NAME?>.
	</div>

	<div class='span1'>
		
	</div>

</div>

