<div class='row-fluid'>

	<div class='span7'>
		<div id="myCarousel" class="carousel slide thusmbnail">
			<!-- Carousel items -->
			<div class="carousel-inner">
			    <div class="active item">
			    	<img class=''  src='<?=HTTP.WWW_ROOT?>/res/img/3.jpg'>		    
			        <div class="carousel-caption">
			          <h1>A Perfect Workout plan</h1>
			        </div>
			    </div>
			    <div class=" item">
			    	<img class='' src='<?=HTTP.WWW_ROOT?>/res/img/4.jpg'>		    
			        <div class="carousel-caption">
			          <h1>Ask Our Expertise</h1>
			        </div>
			    </div>
			    <div class="item">
			    	<img class=''  src='<?=HTTP.WWW_ROOT?>/res/img/5.jpg'>		    
			        <div class="carousel-caption">
			          <h1>Create A Perfect Meal</h1>
			        </div>
			    </div>
			</div>
			<!-- Carousel nav -->
			<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
			<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
		</div>
		
	</div>
	<div class='span5'>
		<iframe class='thumnail span12'
			height="300"
			src="http://vimeo.com/" 
			frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
		</iframe>
	</div>

	
</div>

<div class='row-fluid'>
	<div class='span12 pad40 margin20 white-panel '>
		<div class='span1'>
		</div>

		<div class='span10'>
			<br>
			<br>
			<h2 class='center'>About <span class='black'>Vigor+</span></h2>
			<hr>
			<br>
			<div class='lead'>
				Physical Fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.
				Physical Fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.
				Physical Fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.
			<br>
				<br>
			</div>
		</div>
		<div class='span1'>
		</div>

	</div>
</div>

<div class='row-fluid'>
	<div class='span12 white-panel margin20  pad40 '>
		<div class='span1'>
		</div>
		<div class='span10'>
			<br>
			<br>
			<h2 class='center'>How <span class='black'>It Works.</span></h2>
			<hr>
			<br>
			<div class='lead'>
				Physical Fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.
				Physical Fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.
				Physical Fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.
			<br>
			<br>
			</div>
		</div>
		<div class='span1'>
		</div>
	</div>
</div>

<div class='row-fluid'>
	<div class='span12 white-panel margin20  pad40 '>
		<div class='span1'>
		</div>
		<div class='span10'>
			<br>
			<br>
			<h2 class='center'>For <span class='black'>Businesses!</span></h2>
			<hr>
			<br>
			<div class='lead'>
				Physical Fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.
				Physical Fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.
				Physical Fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.
			<br>
			<br>
			</div>
		</div>
		<div class='span1'>
		</div>
	</div>
</div>

<div class='row-fluid'>
		<br>
</div>
<div class='row-fluid'>
	<div class='span12'>
		<div class='span12 center white-panel'>
			<a class='btn btn-info btn-large' href='<?=HTTP.WWW_ROOT?>/visitor/register'>Signup Now, Its Free !</a>
		</div>
	</div>
</div>
