<div class='span12'>

<h3>Assign Trainee</h3>
<hr><br>
	<div class='row-fluid'>
		
		<form  method='post'  action='' enctype='multipart/form-data'>
			<input type='hidden' name='id' value='<?=$this->id?>'>	
			<?php
			if($this->msg){
				echo "<div class='alert alert-success'>".$this->msg."</div>";
			}
			?>
			<div class='row-fluid'>
				<div class='span12'>
					<div class='span8 test text-info'> Please provide comma ',' separated email of Trainees you want to send invite to.</div>				
					<textarea type="text" class='span8' name='emails' required placeholder="comma separated emails of Trainees here"></textarea>			
				
				</div>		
			</div>
			
			<div class='row-fluid'>
				<div class='span12'>
					<hr>
				</div>
			</div>
			
		
			<button type="submit" class="btn btn-primary"> Submit </button>
							
		</form>
		
	</div>

</div>


