<div class='span12'>

<h3>Edit <?=$this->user->first_name?> <?=$this->user->last_name?></h3>
<hr><br>
	<div class='row-fluid'>
		
		<form  method='post'  action='' enctype='multipart/form-data'>		
			<?php
			if($this->err){
				echo "<div class='alert alert-error'>{$this->err}</div>";
			}
			?>
		
			<div class='row-fluid'>
				<div class='span12 '>
					
					<div class='span4'>
		
						<div class="control-group">
							<div class="controls">						
								<div class="fileupload fileupload-new" data-provides="fileupload">
									<div class="fileupload-new thumbnail" style="width: 150px; height: 150px;">
										<img src='<?=HTTP.WWW_ROOT?>/uploads/<?=$this->user->pic?>'>
									</div>
									<div class="fileupload-preview fileupload-exists thumbnail" 
										style="max-width: 150px; max-height: 150px; line-height: 20px;">
									</div>
									<div>
										<span class="btn btn-file btn-mini">
											<span class="fileupload-new"><i class='icon icon-user'></i> Select Logo</span>
											<span class="fileupload-exists"><i class='icon icon-edit'></i> Change</span>
											<input type="file" name='image'/>
										</span>
										<a href="#" class="btn btn-mini fileupload-exists" data-dismiss="fileupload">
											<i class='icon icon-remove'></i> Remove
										</a>
									</div>
								</div>
								<!-- <div>
									<a href='<?=HTTP.WWW_ROOT?>/admin/users/delete-profile-pic/<?=$this->user->id?>' 
										class='btn btn-danger btn-mini'>Delete Pic</a>
								</div>
								-->
							</div>
						</div>	
							
					</div>
					<div class='span4'>
					
						<p><input type="text" name='email' required placeholder="Email … " value="<?=$this->user->email?>"></p>								<p>
							<?php
							$gender = array('Male', 'Female');
							$Male = $Female = '';
							foreach($gender as $key=>$value){
				        		if($this->user->gender == $value)
				        			$$value = 'checked';
				        			
			   	        	}   	        	
			   	        	?> 
							<label class="radio inline">
							<input required <?=$Male?> type="radio" name="gender"  value="Male" >
								Male
							</label>
							
							<label class="radio inline">
							<input required <?=$Female?> type="radio" name="gender" value="Female">
								Female
							</label>
						</p>

					</div>
					<div class='span4'>
						<p><input type="text" name='first_name' required placeholder="First Name … " value="<?=$this->user->first_name?>"></p>			
						<p><input type="text" name='last_name' required placeholder="Last Name … " value="<?=$this->user->last_name?>"></p>
					
						<p><input type="text" name='mobile' required placeholder="Mobile … " value="<?=$this->user->mobile?>"></p>
						<p><input type="text" name='qualification' required placeholder="Qualification … " value="<?=$this->user->qualification?>"></p>						
					</div>
					
				</div>		
			</div>
			
			<div class='row-fluid'>
				<div class='span12'>
					<hr>
				</div>
			</div>
			
			<button type="submit" class="btn btn-primary"> Submit </button>
							
		</form>
	</div>
</div>

<div class='row-fluid'>

	<div class='span12  white-panel'>
		
		<h3>Trainees assigned to you</h3>
		<hr>
		<?php
		if(count($this->trainee)){
			foreach($this->trainee  as $key=>$value){
				$User = new Model_DbTable_User;
				$trainee = $User->doRead($value->trainee_id);
				echo "<span class='badge badge-success'>{$trainee->email} <a href='".HTTP.WWW_ROOT."/admin/users/delete-trainee/trainee_id/".$value->trainee_id."/id/".$this->user->id."'><i class='icon icon-remove'></i></a></span>";
			}
		}
		else{
			echo "No Trainee assigned.";
		}
		
	
		
		?>		
	</div>
</div>

