<div class='span12 '>

<h3><?=$this->user->first_name?> <?=$this->user->last_name?> Exercises</h3>
<hr><br>
	<div class='row-fluid'>
		
			<?php
			if($this->err){
				echo "<div class='alert alert-error'>{$this->err}</div>";
			}
			?>
		
			<div class='row-fluid'>
				<div class='span12'>
					<div class='span6 white-panel'>					
						<form  method='post'  action='<?=HTTP.WWW_ROOT?>/admin/users/create-exercise' enctype='multipart/form-data'>		
						<input type="hidden" value='<?=$this->user->id?>' name='id'>
						<div class='text text-info'>Select Predefined Exercise</div>
						<hr>
							<p>
							<span class='muted'>Day</span><br>
							<select required name='weekday' style='width:100px'>
			            		<?php
				            	$data = array('Monday'=>1,'Tuesday'=>2,'Wednesday'=>3,'Thursday'=>4,'Friday'=>5,'Saturday'=>6,'Sunday'=>7);
				            	$trans = array_flip($data);
				            	foreach($data as $key=>$value){
					        		echo "<option  value='".$value."'>".$key."</option>";
				   	        	}   	        	
				   	        	?>    
							</select>
							</p>
							<p>
							<span class='muted'>Goal:</span> <?=$this->user->goal?><br>
							</p>
							<p>
							<span class='muted'>Body Type:</span> <?=$this->user->body_type?><br>
							</p>
							<p>
							<span class='muted'>Exercise <small class='text text-info'> (CTRL to multi select)</small>
	</span><br>
							<select required multiple="multiple" class='span8' style='height:150px' name='exercise_id[]' id='exercise_id[]'>
			            		<?php
				            	$data = $this->exercise->fetchAll($this->exercise->select()->order(array('title asc')));
				            	foreach($data as $key=>$value){
					        		echo "<option value='".$value['id']."'>".$value['title']."</option>";
				   	        	}   	        	
				   	        	?>    
							</select>
							</p>
							
					
		
						<button type="submit" class="btn btn-primary"> Submit </button>
								
						</form>					
					</div>
					<div class='span6 white-panel'>
						<form  method='post'  action='<?=HTTP.WWW_ROOT?>/admin/users/create-custom-exercise' enctype='multipart/form-data'>	
						<input type="hidden" value='<?=$this->user->id?>' name='id'>
						
						<div class='text text-info'>Create Custom Exercise</div>
						<hr>
							<div class="control-group pull-right">
								<div class="controls">						
									<div class="fileupload fileupload-new" data-provides="fileupload">
										<div class="fileupload-new thumbnail" style="width: 80px; height: 80px;">
										</div>
										<div class="fileupload-preview fileupload-exists thumbnail" 
											style="max-width: 80px; max-height: 80px; line-height: 20px;">
										</div>
										<div>
											<span class="btn btn-file btn-mini">
												<span class="fileupload-new">Select Image</span>
												<span class="fileupload-exists">Change</span>
												<input type="file" name='pic'/>
											</span>
											<a href="#" class="btn btn-mini fileupload-exists" data-dismiss="fileupload">
												Remove
											</a>
										</div>
									</div>
					
								</div>
							</div>	
		
						<p>
							<span class='muted'>Day</span><br>
							<select required name='weekday' style='width:100px'>
			            		<?php
				            	$data = array('Monday'=>1,'Tuesday'=>2,'Wednesday'=>3,'Thursday'=>4,'Friday'=>5,'Saturday'=>6,'Sunday'=>7);
				            	$trans = array_flip($data);
				            	foreach($data as $key=>$value){
					        		echo "<option  value='".$value."'>".$key."</option>";
				   	        	}   	        	
				   	        	?>    
							</select>
							</p>
							<p><input type="text" name='title' class='span8' required placeholder="title … " value="<?=$this->exercise->title?>"></p>		
						<p><textarea type="text" rows='6' name='description' id='description' class='span8'  placeholder="description … "><?=$this->exercise->description?></textarea></p>		
						
		
						<button type="submit" class="btn btn-primary"> Submit </button>
			
						</form>
					</div>
					
				</div>		
			</div>
			
			<div class='row-fluid'>
				<div class='span12'>
					<hr>
				</div>
			</div>
					
		
	</div>

</div>


<small class='muted'><?=$this->total?> result found. 
</small>
<hr>
<?php echo $this->paginator; ?> 
<br>
<table class='table table-striped table-bordered'>
	<tbody >
		<th style='background-color:#ededed' >
			Weekday
		</th>
		<th style='background-color:#ededed'>
			Exercise
		</th>
		<th style='background-color:#ededed'>
			Description
		</th>
		<th style='background-color:#ededed'>
			Action
		</th>
		
	</tbody>
		<?php
		
		foreach($this->paginator as $key=>$value){
			
			echo "
			<tr>
				<td>
					{$trans[$value->weekday]}
				</td>
				<td>
					{$value->title}
				</td>
				<td>
					{$value->description}
				</td>
				<td class='span3'>			
					<a class='btn btn-mini btn-danger' href='".HTTP.WWW_ROOT."/admin/users/delete-exercise/trainee_id/".$this->user->id."/id/".$value->id."' >Delete</a>";
				echo "</td>
				
			</tr>";
		
		}
		?>
		
</table>

<?php echo $this->paginator; ?>


<link rel="stylesheet" type="text/css" href="<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/lib/css/prettify.css"></link>
<link rel="stylesheet" type="text/css" href="<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/src/bootstrap-wysihtml5.css"></link>

<script src="<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/lib/js/wysihtml5-0.3.0.js"></script>
<script src="<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/lib/js/jquery-1.7.2.min.js"></script>
<script src="<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/lib/js/prettify.js"></script>
<script src="<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/lib/js/bootstrap.min.js"></script>
<script src="<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/src/bootstrap-wysihtml5.js"></script>




<script>
	$('#description').wysihtml5({
		stylesheets:'<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/lib/css/wysiwyg-color.css'
	});
</script>



