<!DOCTYPE html>
<html>
<head>
	<title><?=APP_NAME?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
 	<link href="<?=HTTP.WWW_ROOT?>/lib/bootstrap/css/bootstrap.css" rel="stylesheet">
	<link href="<?=HTTP.WWW_ROOT?>/lib/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
	<script type="text/javascript" src="<?php echo HTTP.WWW_ROOT?>/lib/jquery/jquery.js"></script>
	<script type="text/javascript" src="<?php echo HTTP.WWW_ROOT?>/lib/jquery/jquery.sparklines.js"></script>
	
	<script type="text/javascript" src="<?php echo HTTP.WWW_ROOT?>/lib/bootstrap/js/bootstrap.js"></script>
		
	<link href='http://fonts.googleapis.com/css?family=Bevan' rel='stylesheet' type='text/css'>
	<link href="<?=HTTP.WWW_ROOT?>/lib/bootstrap/css/custom.css" rel="stylesheet">
		
	<script>
	    $(function () {
	        $("[rel='tooltip']").tooltip();
	    });
	</script>
	
	<script>
		function getSubItem(val){
			$.ajax({
				url: "<?=HTTP.WWW_ROOT?>/ajax/get-sub-item/item/"+val, // JSON_URL is a global variable
				dataType: 'json',
				error: function(xhr_data) {},
				success: function(xhr_data){
					//var evald_json  =$.evalJSON(xhr_data);
					var select_box  = document.getElementById('item_id');						
					select_box.options.length = 0;
					d = xhr_data;
					for(var key in d){		
						var i = select_box.options.length++;
						select_box.options[i].text  = d[key].name;
						select_box.options[i].value = d[key].id;
					}
				},
				contentType: 'application/json'
			});
		}

	</script>
	
</head><body>

<div id="myCarousel" class="carousel slide">
	<!-- Carousel items -->
	<div class="carousel-inner">
	    <div class="active item">
	    	<img class='' src='<?=HTTP.WWW_ROOT?>/res/img/13.jpg'>		    
	    </div>
	    <div class="item">
	    	<img class=''  src='<?=HTTP.WWW_ROOT?>/res/img/7.jpg'>		    
	    </div>
	    <div class="item">
	    	<img class=''  src='<?=HTTP.WWW_ROOT?>/res/img/9.jpg'>		    
	    </div>
	</div>
	<!-- Carousel nav -->
</div>

<?php
if(Zend_Auth::getInstance()->hasIdentity()){
?>
<div class="navbar navbar-static-top navbar-inverse">
	<div class="navbar-inner">
		<ul class="nav">
			<li><a href="<?=HTTP.WWW_ROOT?>/user/account/profile">Profile</a></li>
			<li class="divider-vertical"></li>
			<li><a href="<?=HTTP.WWW_ROOT?>/user/meal/plan">My Meal Plans</a></li>
			<li class="divider-vertical"></li>
			<li><a href="<?=HTTP.WWW_ROOT?>/user/meal/progress-chart">Progress Chart</a></li>		      
			<li class="divider-vertical"></li>
			<li><a href="<?=HTTP.WWW_ROOT?>/user/meal/seven-days-out">7 Days Out</a></li>
			<li class="divider-vertical"></li>
		</ul>
		<ul class="nav pull-right">
			<li><a href='<?=HTTP.WWW_ROOT?>/login/quit'>Logout</a></li>    
		</ul>
	</div>
</div>
<?php
}
?>

<div class="container-fluid">
    
	<div class='row-fluid'>
		<div class='span12'>
			<div class='span12' >
				<span class='brand'>
					<a href='<?=HTTP.WWW_ROOT?>'>360<span style='color:#b73c36'><i>Fitness</i></span></a>
				</span>
			</div>
		</div><!-- /btn-span12 -->
	</div>
	
	<div class="row-fluid">
		<div class="span12">
			<hr>
		</div>
	</div>
	
	<div class="row-fluid">
		<div class="span12">
			<?php
				echo $this->layout()->content;	
			?>			
		</div><!--/span-->
	</div><!--/row-->
	
	<div class='row-fluid'>
		<hr>
	</div>
	
		
	<div class='row-fluid center footer-links'>
		<a href='<?=HTTP.WWW_ROOT?>/support/tnc'>Terms & Conditions</a> &nbsp;
		<a href='<?=HTTP.WWW_ROOT?>/support/contact-us'>Contact Us</a>
	</div>
		
	<footer class='center'>
		<p style='color:#ababab;font-size:11px;letter-spacing:1px;'>Copyright © 2013 www.360Fitness.com. All rights reserved.</p>
	</footer>

</div><!--/.fluid-container-->

</body>

</script>
</html>