<!DOCTYPE html>
<html>
<head>
	<title><?=APP_NAME?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
 	<link href="<?=HTTP.WWW_ROOT?>/lib/bootstrap/css/bootstrap.css" rel="stylesheet">
 	<link href="<?=HTTP.WWW_ROOT?>/lib/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
	<script type="text/javascript" src="<?php echo HTTP.WWW_ROOT?>/lib/jquery/jquery.js"></script>
	<script type="text/javascript" src="<?php echo HTTP.WWW_ROOT?>/lib/jquery/jquery.sparklines.js"></script>
	
	<script type="text/javascript" src="<?php echo HTTP.WWW_ROOT?>/lib/bootstrap/js/bootstrap.js"></script>
		
	<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,200,300' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Bevan' rel='stylesheet' type='text/css'>
	<link href="<?=HTTP.WWW_ROOT?>/lib/bootstrap/css/custom.css" rel="stylesheet">
	
	<script src="https://maps.google.com/maps/api/js?sensor=false"></script>
	<script type="text/javascript" src="<?=HTTP.WWW_ROOT?>/lib/map/jquery.gmap.min.js"></script>
	<script type="text/javascript" src="<?=HTTP.WWW_ROOT?>/lib/map/jquery.ui.map.js"></script>
		
	<script>
	    $(function () {
	        $("[rel='tooltip']").tooltip();
	    });
	</script>
	
	<script>
		function getSubItem(val){
			$.ajax({
				url: "<?=HTTP.WWW_ROOT?>/ajax/get-sub-item/item/"+val, // JSON_URL is a global variable
				dataType: 'json',
				error: function(xhr_data) {},
				success: function(xhr_data){
					//var evald_json  =$.evalJSON(xhr_data);
					var select_box  = document.getElementById('item_id');						
					select_box.options.length = 1;
					
					select_box.options[0].text = '';
					select_box.options[0].value = '';
					
					d = xhr_data;
					for(var key in d){		
						var i = select_box.options.length++;
						select_box.options[i].text  = d[key].name;
						select_box.options[i].value = d[key].id;
					}
				},
				contentType: 'application/json'
			});
		}
		function getSubItemUnits(val){
			$.ajax({
				url: "<?=HTTP.WWW_ROOT?>/ajax/get-sub-item-units/item/"+val, // JSON_URL is a global variable
				dataType: 'json',
				error: function(xhr_data) {},
				success: function(xhr_data){
					//var evald_json  =$.evalJSON(xhr_data);
					var select_box  = document.getElementById('item_units_id');						
					select_box.options.length = 1;
					
					select_box.options[0].text = '';
					select_box.options[0].value = '';
					
					d = xhr_data;
					for(var key in d){		
						var i = select_box.options.length++;
						select_box.options[i].text  = d[key].weight_unit;
						select_box.options[i].value = d[key].id;
					}
				},
				contentType: 'application/json'
			});
		}
		function getSubItemQty(val){
			$.ajax({
				url: "<?=HTTP.WWW_ROOT?>/ajax/get-sub-item-qty/item/"+val, // JSON_URL is a global variable
				dataType: 'json',
				error: function(xhr_data) {},
				success: function(xhr_data){
					//var evald_json  =$.evalJSON(xhr_data);
					var select_box  = document.getElementById('item_qty_id');						
					select_box.options.length = 1;
					
					select_box.options[0].text = '';
					select_box.options[0].value = '';
					
					d = xhr_data;
					for(var key in d){		
						var i = select_box.options.length++;
						select_box.options[i].text  = d[key].weight;
						select_box.options[i].value = d[key].id;
					}
				},
				contentType: 'application/json'
			});
		}

	</script>
	
</head><body>

	<?php
	$TrainerTrainee = new Model_DbTable_Trainer_Trainee;
	$User = new Model_DbTable_User;
	$Auth = $User->doRead(Zend_Auth::getInstance()->getStorage()->read()->id);
	
	$MyTrainer = $TrainerTrainee->getTrainer($Auth->id);
?>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
     <a class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
       <a href='<?=HTTP.WWW_ROOT?>/'><span class='brand white'>Vigor<span class='blue bold'> +</span></span></a>
     	<div class="nav-collapse">
         <ul class="nav">
			<?php
			if(Zend_Auth::getInstance()->hasIdentity()){
			?>
			
			<li><a href="<?=HTTP.WWW_ROOT?>/user/account/profile">Profile</a></li>
			<li class="divider-vertical"></li>
			<li><a href="<?=HTTP.WWW_ROOT?>/user/meal/plan">My Meal Plans</a></li>
			<li class="divider-vertical"></li>
			<li><a href="<?=HTTP.WWW_ROOT?>/user/meal/workout">My Workout</a></li>
			<li class="divider-vertical"></li>
			<li><a href='' data-content="<form action='<?=HTTP.WWW_ROOT?>/user/meal/progress-chart' method='post'>
					<input name='weight_lbs' type='text' value='<?=$Auth->weight_lbs?>'  class='input-medium' placeholder='weight in lbs'><br><button type='submit' class='btn btn-primary'>Go</button>
					</form>" class='progress_chart_popover' data-title='Enter Your Current Weight in lbs' data-toggle='modal' role='button'  >Progress Chart</a></li>		      
			<li class="divider-vertical"></li>
			<li><a href="<?=HTTP.WWW_ROOT?>/user/meal/seven-days-out">7 Days Out</a></li>
			<li class="divider-vertical"></li>
          	<?php
          	}
          	?>
          </ul>
          <ul class="nav pull-right">
			<?php
			if(Zend_Auth::getInstance()->hasIdentity()){
			?>
			<li><a href='<?=HTTP.WWW_ROOT?>/login/quit' ><span class='red'>Logout</span></a></li>    
          	<?php
          	}
          	else{
          	?>
			<li><a href='<?=HTTP.WWW_ROOT?>/login' ><span class='blue'>Login</span></a></li>              	
          	<?php
          	}
          	?>
          </ul>
          
       </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container-fluid">    
    <div class='row-fluid'>
	<div class='span12 '>
		<br>
		<?php
		if(Zend_Auth::getInstance()->hasIdentity()){
		?>
		<div class='pull-right blue'>Welcome, <?=$Auth->first_name?> <?=$Auth->last_name?>.</div>
	
		<?php
		}
		?>
		<?php
		if(Zend_Auth::getInstance()->hasIdentity()){
		?>		
			<div class='pull-left muted'>
			<small>
			Goal: <?=$Auth->goal?> |
			Body Type: <?=$Auth->body_type?>
			</small>
			</div>
		<?php
		}
		?>
	</div>
	</div>	

	<div class="row-fluid">
		<div class="span12 border-panel">
			<?php
				echo $this->layout()->content;	
			?>			
		</div><!--/span-->
	</div><!--/row-->
	
	<div class='row-fluid'>
		<hr>
	</div>
	
		
	<div class='row-fluid center footer-links'>
		<a href='<?=HTTP.WWW_ROOT?>/support/faq'>FAQ</a> &nbsp;
		<a href='<?=HTTP.WWW_ROOT?>/support/tnc'>Terms & Conditions</a> &nbsp;
		<a href='<?=HTTP.WWW_ROOT?>/support/contact-us'>Contact</a>
	</div>
		
	<footer class='center'>
		<p style='color:#ababab;font-size:11px;letter-spacing:1px;'>Copyright © 2013 www.Vigor.com. All rights reserved.</p>
	</footer>

</div><!--/.fluid-container-->


</body>

</html>


<script>
	
	$(function(){
	
		$("#print").click(function(){
			window.print();
			return false;
		});
		
	    
	    $(".meal_edit_popover").popover({
	            placement: 'right',
	            html: 'true'
	    });

	    $(".progress_chart_popover").popover({
	            placement: 'bottom',
	            html: 'true'
	    });

	    $(".meal_add_popover").popover({
	            placement: 'right',
	            html: 'true'	 
	    });
	    
		$(':not(#anything)').on('click', function (e) {
		    $('.meal_edit_popover').each(function () {
		        if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
		            $(this).popover('hide');
		            return;
		        }
		    });
		});

		$(':not(#anything)').on('click', function (e) {
		    $('.progress_chart_popover').each(function () {
		        if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
		            $(this).popover('hide');
		            return;
		        }
		    });
		});
		
	    $(':not(#anything)').on('click', function (e) {
		    $('.meal_add_popover').each(function () {
		        if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
		            $(this).popover('hide');
		            return;
		        }
		    });
		});
	    

		/*
		$('.popover_close').click(function(){
           alert('11');
           $('.meal_edit_popover').popover('hide');
        });
		*/
	});
	
	function date_time(id)
	{
	        date = new Date;
	        year = date.getFullYear();
	        month = date.getMonth();
	        months = new Array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
	        d = date.getDate();
	        day = date.getDay();
	        days = new Array('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday');
	        h = date.getHours();
	        if(h<10)
	        {
	                h = "0"+h;
	        }
	        m = date.getMinutes();
	        if(m<10)
	        {
	                m = "0"+m;
	        }
	        s = date.getSeconds();
	        if(s<10)
	        {
	                s = "0"+s;
	        }
	        result = ''+days[day]+' '+months[month]+' '+d+' '+year+', '+h+':'+m+':'+s;
	        document.getElementById(id).innerHTML = result;
	        setTimeout('date_time("'+id+'");','1000');
	        return true;
	}


</script>
<script type="text/javascript">window.onload = date_time('date_time');</script>
  

