<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?=APP_NAME?></title>
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link href="<?=HTTP.WWW_ROOT?>/lib/bootstrap/css/bootstrap.css" rel="stylesheet">
	<link href="<?=HTTP.WWW_ROOT?>/lib/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
	<script type="text/javascript" src="<?php echo HTTP.WWW_ROOT?>/lib/jquery/jquery.js"></script>
	
	<script type="text/javascript" src="<?php echo HTTP.WWW_ROOT?>/lib/bootstrap/js/bootstrap.js"></script>
		
	<link href="<?php echo HTTP.WWW_ROOT?>/lib/bootstrap/css/admin.css" rel="stylesheet">
	<script>
   		$(function () {
    	    $("[rel='tooltip']").tooltip();
    	});
	</script>
	
	<style>
		body{
			padding-top: 60px;
		}
	</style>
</head>
<body>

    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>	
            <span class="icon-bar"></span>
          </a>
 			<a class="brand">
 				360 Fitness
 			</a>
           
           <div class="nav-collapse">
            <ul class="nav">
             <li><a href="<?=HTTP.WWW_ROOT?>/trainer/account/profile">My Profile</a></li>
             <li><a href="<?=HTTP.WWW_ROOT?>/trainer/trainee/list">My Trainees</a></li>
             
              <?php
              	if(Zend_Auth::getInstance()->hasIdentity()){
              ?>
              		<li><a href="<?=HTTP.WWW_ROOT?>/login/quit" style='color:#dc443f'> logout </a></li>
              
              <?php
              	}
              	else{
              	
              ?>
              		<li><a href="<?=HTTP.WWW_ROOT?>/login"> login </a></li>
               <?php
               }
               ?>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

	<div class="container-fluid">		
	  
	  <div class='row-fluid'>
		  <div class='span12'>
		  <?php
		  	echo $this->layout()->content;
		  	
		  ?>
		  </div>
	  </div>
	  
      <div class="footer" style='color:#bababa'>
      	<br><br><hr>
      	Copyright. 360 Fitness 2013.  
      	
      </div>


    </div> <!-- /container -->

</body>
    
</html>

