	<div class='alert alert-danger'>
		<h4>Are you sure you want to delete '<?=$this->FlightData->name?>'</h4>
	</div>
	<br>
	<br><br>
	<a class='btn btn-danger btn-large' href='<?=HTTP.WWW_ROOT?>/admin/flight/delete/id/<?=$this->FlightData->id?>'>Yes, Delete '<?=$this->FlightData->name?>'.</a>
	<a class='btn btn-warning btn-large' href='<?=HTTP.WWW_ROOT?>/admin/flight/list'>No, Go back!</a>

<br><br><br><br>