<div class='span12 white-panel'>
<div class="btn-group pull-right" data-toggle="buttons-checkbox">
	<a class="btn" href='<?=HTTP.WWW_ROOT?>/admin/exercise/list'>Create New Exercise <i class='icon icon-chevron-right'></i></a>
</div>	

<h3>Set Default Exercises</h3>
<hr><br>
	<div class='row-fluid'>
		
		<form  method='post'  action='<?=HTTP.WWW_ROOT?>/admin/exercise/create-default' enctype='multipart/form-data'>		
			<?php
			if($this->err){
				echo "<div class='alert alert-error'>{$this->err}</div>";
			}
			?>
		
			<div class='row-fluid'>
				<div class='span12  '>
					
					<div class='span4'>
						<p>
						<span class='muted'>Day</span><br>
						<select required name='weekday' style='width:100px'>
		            		<?php
			            	
			            	$data = array('Monday'=>1,'Tuesday'=>2,'Wednesday'=>3,'Thursday'=>4,'Friday'=>5,'Saturday'=>6,'Sunday'=>7);
			            	
			            	$trans = array_flip($data);
			            	
			            	foreach($data as $key=>$value){
				        		echo "<option  value='".$value."'>".$key."</option>";
			   	        	}   	        	
			   	        	?>    
						</select>
						</p>
						<p>
						<span class='muted'>Goal:</span><br>
						<select required name='goal' id='goal'>
		            		<?php
			            	$data = $this->goal->fetchAll($this->goal->select()->order(array('name asc')));
			            	foreach($data as $key=>$value){
				   	    		echo "<option  value='".$value['name']."'>".$value['name']."</option>";
			   	        	}   	        	
			   	        	?>    
						</select>
						</p>
						<p>
						<span class='muted'>Body Type:</span><br>
						<select required name='body_type' id='body_type'>
		            		<?php
			            	$data = $this->body_type->fetchAll($this->body_type->select()->order(array('name asc')));
			            	foreach($data as $key=>$value){
				        		echo "<option  value='".$value['name']."'>".$value['name']."</option>";
			   	        	}   	        	
			   	        	?>    
						</select>
						</p>
						<p>
							<label class="radio inline">
							<input required  type="radio" name="gender"  value="Male" >
								Male
							</label>
							
							<label class="radio inline">
							<input required  type="radio" name="gender" value="Female">
								Female
							</label>
						</p>
					</div>
					<div class='span8'>
						<p>
						<span class='muted'>Exercise <small class='text text-info'> (CTRL to multi select)</small>
</span><br>
						<select required multiple="multiple" class='span8' style='height:200px' name='exercise_id[]' id='exercise_id[]'>
		            		<?php
			            	$data = $this->exercise->fetchAll($this->exercise->select()->order(array('title asc')));
			            	foreach($data as $key=>$value){
				        		echo "<option value='".$value['id']."'>".$value['title']."</option>";
			   	        	}   	        	
			   	        	?>    
						</select>
						</p>
						
					</div>
					
				</div>		
			</div>
			
			<div class='row-fluid'>
				<div class='span12'>
					<hr>
				</div>
			</div>
			
		
			<button type="submit" class="btn btn-primary"> Submit </button>
							
		</form>
		
	</div>

</div>

<small class='muted'><?=$this->total?> result found. 
</small>
<hr>
<?php echo $this->paginator; ?> 
<br>
<table class='table table-striped table-bordered'>
	<tbody >
		<th style='background-color:#ededed' >
			Weekday
		</th>
		<th style='background-color:#ededed' >
			Body Type
		</th>
		<th style='background-color:#ededed' >
			Gender
		</th>
		<th style='background-color:#ededed'>
			Goal
		</th>
		<th style='background-color:#ededed'>
			Exercise
		</th>
		<th style='background-color:#ededed'>
			Action
		</th>
		
	</tbody>
		<?php
		
		foreach($this->paginator as $key=>$value){
			
			$exercise = $this->exercise->doRead($value->exercise_id);
			echo "
			<tr>
				<td>
					{$trans[$value->weekday]}
				</td>
				<td >
					{$value->body_type}
				</td>
				<td>
					{$value->gender}
				</td>
				<td>
					{$value->goal}
				</td>
				<td>
					{$exercise->title}
				</td>
				<td class='span3'>			
					<a class='btn btn-mini btn-danger' href='".HTTP.WWW_ROOT."/admin/exercise/delete-confirm-default/id/".$value->id."' >Delete</a>";
				echo "</td>
				
			</tr>";
		
		}
		?>
		
</table>

<?php echo $this->paginator; ?>



