<link rel="stylesheet" type="text/css" href="<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/lib/css/prettify.css"></link>
<link rel="stylesheet" type="text/css" href="<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/src/bootstrap-wysihtml5.css"></link>

<script src="<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/lib/js/wysihtml5-0.3.0.js"></script>
<script src="<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/lib/js/jquery-1.7.2.min.js"></script>
<script src="<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/lib/js/prettify.js"></script>
<script src="<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/lib/js/bootstrap.min.js"></script>
<script src="<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/src/bootstrap-wysihtml5.js"></script>

<div class='row-fluid'>
	<div class="btn-group pull-right" data-toggle="buttons-checkbox">
		<a class="btn" href='<?=HTTP.WWW_ROOT?>/admin/exercise/default'>Set Defaults For User Profile <i class='icon icon-chevron-right'></i></a>
	</div>	

	<h3><?=$this->title?></h3>
	
	<hr><br>
	<div class='row-fluid '>
		<form  method='post'  action='<?=$this->formaction?>' enctype='multipart/form-data'>		
			<?php
			if($this->err){
				echo "<div class='alert alert-error'>{$this->err}</div>";
			}
			?>
		
			<div class='row-fluid '>
				<div class='span12'>
					
					<div class='span4'>
		
						<div class="control-group">
							<div class="controls">						
								<div class="fileupload fileupload-new" data-provides="fileupload">
									<div class="fileupload-new thumbnail" style="width: 150px; height: 150px;">
									<?php
									if($this->exercise->pic){
									?>
										<img src='<?=HTTP.WWW_ROOT?>/uploads/<?=$this->exercise->pic?>' alt='image'>
									<?php
									}
									?>
									</div>
									<div class="fileupload-preview fileupload-exists thumbnail" 
										style="max-width: 150px; max-height: 150px; line-height: 20px;">
									</div>
									<div>
										<span class="btn btn-file btn-mini">
											<span class="fileupload-new">Select Image</span>
											<span class="fileupload-exists">Change</span>
											<input type="file" name='pic'/>
										</span>
										<a href="#" class="btn btn-mini fileupload-exists" data-dismiss="fileupload">
											Remove
										</a>
									</div>
								</div>
				
							</div>
						</div>	
							
					</div>
					<div class='span8'>
					
						<p><input type="text" name='title' class='span10' required placeholder="title … " value="<?=$this->exercise->title?>"></p>		
						<p><textarea type="text" rows='6' name='description' id='description' class='span10'  placeholder="description … "><?=$this->exercise->description?></textarea></p>		
					</div>
					
				</div>		
			</div>
			
		
			<button type="submit" class="btn btn-primary"> Submit </button>
		
		</div>			
		</form>
		<hr>
	</div>

</div>

<h3>All Exercises</h3>
<small class='muted'><?=$this->total?> result found. 
</small>
<?php echo $this->paginator; ?> 
<br>
<table class='table table-striped table-bordered'>
	<tbody >
		<th style='background-color:#ededed' >
			Image
		</th>
		<th style='background-color:#ededed' >
			Title
		</th>
		<th style='background-color:#ededed' >
			Description
		</th>
		<th style='background-color:#ededed'>
			Action
		</th>
		
	</tbody>
		<?php
		
		foreach($this->paginator as $key=>$value){
			
			echo "
			<tr>
				<td width='10%'>
					<img class='thumbnail span12' src='".HTTP.WWW_ROOT."/uploads/{$value->pic}'>
					<br>
					<center><a href='".HTTP.WWW_ROOT."/admin/exercise/delete-image/id/".$value->id."'><i class='icon-remove'></i></a></center>
				</td>
				<td width='30%'>
					{$value->title}
				</td>
				<td width='40%'>
					{$value->description}
				</td>
				<td class='span3'>
					<a class='btn btn-mini btn-danger' href='".HTTP.WWW_ROOT."/admin/exercise/delete-confirm/id/".$value->id."' >Delete</a>
					<a class='btn btn-mini ' href='".HTTP.WWW_ROOT."/admin/exercise/list/id/".$value->id."' >Edit</a>";
				echo "</td>
				
			</tr>";
		
		}
		?>
		
</table>

<?php echo $this->paginator; ?>

<script>
	$('#description').wysihtml5({
		stylesheets:'<?=HTTP.WWW_ROOT?>/lib/bootstrap-editor/lib/css/wysiwyg-color.css'
	});
</script>




