<h4>Request New Feature</h4>
<form  method='post' action='' enctype="multipart/form-data" class='well'>		
		<div class="control-group">
			<div class="controls input-append">
				<textarea type="text"  id="ingredients" name='ingredients' rows='8' class='span8' placeholder="description of feature you would like to have ..."></textarea>
				<span class="add-on"> … required</span>
			</div>
		</div>	
	<div class='row'></div>
	
	<div class="form-actions">
	    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    
</form>

