
<div class='row-fluid'>
	<div class='span12 well'>
		<div id="chart_div_1" class='center span12' style="height: 300px;"></div>
	</div>
</div>

<div class='row-fluid'>
	<div class='span12 well'>
	    <div id="chart_div_2" class='center span12' style="height: 300px;"></div>
	</div>
</div>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load('visualization', '1', {packages: ['corechart']});

//-----------CHART 1---------------

  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['Time', 'Weight in lbs'],
      
    <?php	
      $i = 1;
      foreach($this->user_weight_data as $key=>$value){
      	echo "['".$i."', ".$value['weight_lbs']." ],";
      	$i++;
      }
    ?>
    ]);
    
    var options = {
      title: 'Last 30 Days Weight Report',
      hAxis: { title: "Day", format: 'm/d/y'},
      series: {
        0:{ type: "line", targetAxisIndex: 0}
      },
      pointSize : 5,

    }

    var chart = new google.visualization.LineChart(document.getElementById('chart_div_1'));
    chart.draw(data, options);
  }
  google.setOnLoadCallback(drawChart);



//-----------CHART 2---------------
  
  function drawVisualization() {
  
    // Some raw data (not necessarily accurate)
    var data = google.visualization.arrayToDataTable([
      ['Month', 'Actual', 'Target'],
      ['Week1',  1890,      1950 ],
      ['Week2',  1955,      1950 ],
      ['Week3',  2030,      1950 ],
      ['Week4',  1890,      1950 ],
      ['Week5',  2010,      1950]
    ]);

  
  	var options = {
      title : 'Weekly Average Calorie Intake',
      vAxis: {title: "Calories"},
      hAxis: {title: "Week"},
      seriesType: "bars",
      series: {2: {type: "line"}}
    };

    var chart = new google.visualization.ComboChart(document.getElementById('chart_div_2'));
    chart.draw(data, options);
  
  }

  google.setOnLoadCallback(drawVisualization);

</script>

