<div class='pull-right'>
<a href='<?=HTTP.WWW_ROOT?>/user/meal/exercise' class='btn btn-info'>Customize Workout <i class='icon-arrow-right'></i></a>
</div>
<div class='row-fluid'>
<div class='span12'>
	
<hr>
<br>
	<?php
	if(count($this->data)){
		foreach($this->data as $key=>$value){
		?>		
			<div class='row-fluid'>
			<div class='span12'>
			<div class='span3'><img class='span10 thumbnail' src='<?=HTTP.WWW_ROOT?>/uploads/<?=$value->pic?>' alt='NO IMAGE'></div>
			<div class='span9'>
				<div class='row-fluid'>
					<div class='span12'>
						<div class=''><h3 class=''><?=$value->title?></h3></div>
						<div class=''><?=$value->description?></div>
					</div>
				</div>
			</div>
			</div>
			</div>
			<br><hr><br>
		<?php
		}
	}
	else{
		echo "<div class='text text-info'>Nothing for today</div>";
	}
	?>
	<br>
</div>
</div>

